# Generated by Django 5.1.3 on 2024-11-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('employee', 'Employee')], default='user', max_length=255),
        ),
    ]
